### ISSUE TITLE
not found: type MapRepetitiveRegions

### ISSUE THREAD

**Issue by hjeanc** [YeoLab/gscripts#70]
I'm unable to run `analyze_rna_seq.scala` because of a missing definition. [Here's a link to a gist](https://gist.github.com/hjeanc/eee5d2edfb79a4560555) with the output logs, a bit of the manifest file, the sh script, and all the recent git logs. We have the most updated version of both GATK queue and gscript

**Comment by gpratt** [comment]
update gatk queue again please, Also do another pull on gscripts.
MapRepetitiveRegions shouldn't actually be called anymore.  I'm confused as
to why it is.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
did you re-build gatk queue?

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by hjeanc** [comment]
yes with `ant clean dist`

**Comment by hjeanc** [comment]
no updates in gscripts, `git pull origin master` says up to date

**Comment by gpratt** [comment]
Update gscripts again.  Should work.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by hjeanc** [comment]
Thanks!!!
