### ISSUE TITLE
where is featureCounts?

### ISSUE THREAD

**Issue by ecwheele** [YeoLab/gscripts#78]
I have tried two different directories:
/projects/ps-yeolab/software/bin/featureCounts

and 

/projects/ps-yeolab/software/subread-1.4.5-source/bin/featureCounts

and both times I got the error message: no match.

Where is the current working version of featureCounts?

**Comment by LJamal** [comment]
You can run feature counts like this:

featureCounts -M -a
/projects/ps-yeolab/genomes/hg19/gencode_v19/gencode.v19.annotation.gtf -o
youroutfile.txt *sorted.bam

you just need to specify if you want multimapping -M
the annotation file -a
your output file -o

run it in the dir containing your sorted.bam files
depending on how many files you have, you may want to login to a node
